#pragma once
#ifndef __FLAMINGO_KEYS_H__
#define __FLAMINGO_KEYS_H__
#include <SDL_keycode.h>
namespace Flamingo{

    typedef Sint32 FLM_Keycode;

    typedef enum
    {
        FLM_UNKNOWN = SDLK_UNKNOWN,
        FLM_RETURN = SDLK_RETURN,
        FLM_ESCAPE = SDLK_ESCAPE,
        FLM_BACKSPACE = SDLK_BACKSPACE,
        FLM_TAB = SDLK_TAB,
        FLM_SPACE = SDLK_SPACE,
        FLM_EXCLAIM = SDLK_EXCLAIM,
        FLM_QUOTEDBL = SDLK_QUOTEDBL,
        FLM_HASH = SDLK_HASH,
        FLM_PERCENT = SDLK_PERCENT,
        FLM_DOLLAR = SDLK_DOLLAR,
        FLM_AMPERSAND = SDLK_AMPERSAND,
        FLM_QUOTE = SDLK_QUOTE,
        FLM_LEFTPAREN = SDLK_LEFTPAREN,
        FLM_RIGHTPAREN = SDLK_RIGHTPAREN,
        FLM_ASTERISK = SDLK_ASTERISK,
        FLM_PLUS = SDLK_PLUS,
        FLM_COMMA = SDLK_COMMA,
        FLM_MINUS = SDLK_MINUS,
        FLM_PERIOD = SDLK_PERIOD,
        FLM_SLASH = SDLK_SLASH,
        FLM_0 = SDLK_0,
        FLM_1 = SDLK_1,
        FLM_2 = SDLK_2,
        FLM_3 = SDLK_3,
        FLM_4 = SDLK_4,
        FLM_5 = SDLK_5,
        FLM_6 = SDLK_6,
        FLM_7 = SDLK_7,
        FLM_8 = SDLK_8,
        FLM_9 = SDLK_9,
        FLM_COLON = SDLK_COLON,
        FLM_SEMICOLON = SDLK_SEMICOLON,
        FLM_LESS = SDLK_LESS,
        FLM_EQUALS = SDLK_EQUALS,
        FLM_GREATER = SDLK_GREATER,
        FLM_QUESTION = SDLK_QUESTION,
        FLM_AT = SDLK_AT,

        FLM_LEFTBRACKET = SDLK_LEFTBRACKET,
        FLM_BACKSLASH = SDLK_BACKSLASH,
        FLM_RIGHTBRACKET = SDLK_RIGHTBRACKET,
        FLM_CARET = SDLK_CARET,
        FLM_UNDERSCORE = SDLK_UNDERSCORE,
        FLM_BACKQUOTE = SDLK_BACKQUOTE,
        FLM_a = SDLK_a,
        FLM_b = SDLK_b,
        FLM_c = SDLK_c,
        FLM_d = SDLK_d,
        FLM_e = SDLK_e,
        FLM_f = SDLK_f,
        FLM_g = SDLK_g,
        FLM_h = SDLK_h,
        FLM_i = SDLK_i,
        FLM_j = SDLK_j,
        FLM_k = SDLK_k,
        FLM_l = SDLK_l,
        FLM_m = SDLK_m,
        FLM_n = SDLK_n,
        FLM_o = SDLK_o,
        FLM_p = SDLK_p,
        FLM_q = SDLK_q,
        FLM_r = SDLK_r,
        FLM_s = SDLK_s,
        FLM_t = SDLK_t,
        FLM_u = SDLK_u,
        FLM_v = SDLK_v,
        FLM_w = SDLK_w,
        FLM_x = SDLK_x,
        FLM_y = SDLK_y,
        FLM_z = SDLK_z,

        FLM_CAPSLOCK = SDLK_CAPSLOCK,

        FLM_F1 = SDLK_F1,
        FLM_F2 = SDLK_F2,
        FLM_F3 = SDLK_F3,
        FLM_F4 = SDLK_F4,
        FLM_F5 = SDLK_F5,
        FLM_F6 = SDLK_F6,
        FLM_F7 = SDLK_F7,
        FLM_F8 = SDLK_F8,
        FLM_F9 = SDLK_F9,
        FLM_F10 = SDLK_F10,
        FLM_F11 = SDLK_F11,
        FLM_F12 = SDLK_F12,

        FLM_PRINTSCREEN = SDLK_PRINTSCREEN,
        FLM_SCROLLLOCK = SDLK_SCROLLLOCK,
        FLM_PAUSE = SDLK_PAUSE,
        FLM_INSERT = SDLK_INSERT,
        FLM_HOME = SDLK_HOME,
        FLM_PAGEUP = SDLK_PAGEUP,
        FLM_DELETE = SDLK_DELETE,
        FLM_END = SDLK_END,
        FLM_PAGEDOWN = SDLK_PAGEDOWN,
        FLM_RIGHT = SDLK_RIGHT,
        FLM_LEFT = SDLK_LEFT,
        FLM_DOWN = SDLK_DOWN,
        FLM_UP = SDLK_UP,

        FLM_NUMLOCKCLEAR = SDLK_NUMLOCKCLEAR,
        FLM_KP_DIVIDE = SDLK_KP_DIVIDE,
        FLM_KP_MULTIPLY = SDLK_KP_MULTIPLY,
        FLM_KP_MINUS = SDLK_KP_MINUS,
        FLM_KP_PLUS = SDLK_KP_PLUS,
        FLM_KP_ENTER = SDLK_KP_ENTER,
        FLM_KP_1 = SDLK_KP_1,
        FLM_KP_2 = SDLK_KP_2,
        FLM_KP_3 = SDLK_KP_3,
        FLM_KP_4 = SDLK_KP_4,
        FLM_KP_5 = SDLK_KP_5,
        FLM_KP_6 = SDLK_KP_6,
        FLM_KP_7 = SDLK_KP_7,
        FLM_KP_8 = SDLK_KP_8,
        FLM_KP_9 = SDLK_KP_9,
        FLM_KP_0 = SDLK_KP_0,
        FLM_KP_PERIOD = SDLK_KP_PERIOD       
    } FLM_KeyCode;
} // namespace Flamingo
#endif